name: Publish
on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish a Package
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN --verbose
          npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
