name: Validate that changes not break bundling workflow
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
      - name: Retrieve Scripts
        run: |
          git clone https://github.com/forcedotcom/bundle-publish-scripts.git
      - name: Update for Publishing
        run: |
          node bundle-publish-scripts/scripts/updateForCoreBundle.js
      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
      - name: Run Build within the Project
        run: |
          yarn build
      - name: Run Tests within the Project
        run: |
          yarn test