name: Validate that changes not break bundling workflow
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build with core-bundle
        uses: forcedotcom/bundle-publish-scripts/.github/actions/buildWithCoreBundle@main
      - name: Run Tests within the Project
        run: |
          yarn test